Class bplus.tool.producao Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="bplus.tool.producao" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="bplusTOOL" Category="" ClassName="bplus.tool.BP.Tool" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="true" Schedule="">
  </Item>
</Production>
}

}
