services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972:1972
      - 52773:52773
      - 53773:53773
    volumes:
      - ./:/home/irisowner/dev
    environment: 
      - SCHEMA_COLLECTION=$SCHEMA_COLLECTION
      - SAMPLE_COLLECTION=$SAMPLE_COLLECTION
    networks:
      - app-network 
networks:
  app-network:  # Define a rede `app-network`
    driver: bridge